USE mysql;
CREATE DATABASE IF NOT EXISTS dev;
CREATE DATABASE IF NOT EXISTS stage;
CREATE DATABASE IF NOT EXISTS test;
CREATE USER "mb"@"%" IDENTIFIED BY "mb";
ALTER USER "mb"@"%" IDENTIFIED WITH mysql_native_password BY "mb";
FLUSH PRIVILEGES;

GRANT ALL ON *.* TO "mb"@"%";
FLUSH PRIVILEGES;